# Generated by Django 3.2.9 on 2021-11-13 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_num', models.CharField(max_length=15)),
                ('name', models.CharField(default=models.CharField(max_length=15), max_length=60)),
                ('email_address', models.EmailField(blank=True, default='', max_length=320)),
            ],
        ),
        migrations.CreateModel(
            name='ContactList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('contacts', models.ManyToManyField(related_name='contact_list', to='contacts.Contact')),
            ],
        ),
    ]
