# Generated by Django 3.2.9 on 2021-11-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactlist',
            name='contacts',
        ),
        migrations.AddField(
            model_name='contactlist',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='contact_list', to='contacts.Contact'),
        ),
        migrations.DeleteModel(
            name='ContactListDetail',
        ),
    ]
